const data = [
  {
    title: "Bois",
    icon: "bi-gear-fill",
    childrens: [
      {
        id: 2,
        title: "Bois-Rouge",
        path: "/produits/BOIS-ROUGE/1",
        data: {
          image: "/assets/bois-rouge.jpg",
          images: [
            {
              img1: "/assets/Bbcadre.jpg",
              img2: "/assets/BbPallete.jpg",
              img3: "/assets/BbTouret.jpg",
              img4: "/assets/Bbcolle.jpg",
            },
          ],
          category: "bois-rouge",
          desc: "Habitat dispose d’un stock important de bois rouge, importé de Suède et Finlande.C’est sa facilité et sa rapidité d’usinage qui permet la réalisation d’ouvrages les plus variés.Très durable en raison de sa teneur en résine ; accroissement annuels très serrés ce qui lui donne une très bonne résistance mécanique.Le Sapin est recommandé pour tous les travaux de charpentee",
          essences: "Pin Sylvestre",
          utilisations:
            "portes, fenêtres, lambris assemblés, parquets, moulures, plinthes, bâtis et huisseries.",
          DENSITÉ: "0,50 à 0,60 – tendre",
          livraison: "Oui",
          PROVENANCES: "Stenvalls,Camab,Ersa,Gosta,Polkky",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.4--->5.4",
          epaisseur: "20-25-40-45-47-50-75",
          larg: "75-->225",
        },
      },

      {
        title: "BOIS-BLANC",
        icon: "bi-gear-fill",
        path: "/produits",
        childrens: [
          {
            id: 1,
            title: "Madrier",
            path: "/produits/BOIS-BLANC/1",
            data: {
              image: "/assets/Madrier.png",
              images: [
                {
                  img1: "/assets/BbTerrase.jpg",
                  img2: "/assets/BbAbris.jpg",
                  img3: "/assets/BbDecorat.jpg",
                  img4: "/assets/BbDivers.jpg",
                },
              ],
              category: "bois-blanc",
              desc: "C’est le Bois Blanc destiné pour la construction immobilière, servant au coffrage et Bois de structure.Bois supportant de hautes températures. En Maroc, il est très utilisé en menuiserie dont il assure une gamme d’ouvrage très étendue : portes, châssis, casiers.Trouve également son emploi en charpentes de toutes natures. Ceux qui ont les veines d’accroissement les plus serrées, sont très recherchés  pour la lutherie : table de violon, violoncelle… Sert également à la fabrication d’échelles, moulures, parquets, et lambris. Très utilisé pour la pâte à papier.",
              essences: "Sapin ou Epicéa",
              utilisations:
                "- structure de terrasse bois, en particulier dans les cas de terrasse surélevée, ou pour rattraper des hauteurs.- pergolas et abris - usages extérieurs divers, décoratifs ou de structure (retenue de terre,...). ",
              DENSITÉ:
                "la masse volimique: 530 kg/m3,présente une densité avoisinant 0.5",
              livraison: "Oui",
              PROVENANCES: "AV-ASIE WOOD-GR-MM-SOCOREG",
              RÉSISTANCE:
                "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
              classes: "I,V,III,Shall,VII",
              long: "3-4",
              matiere: "Bois massif",
              epaisseur: "20-25-40-45-47-50",
              larg: "150-175-200-225",
            },
          },
          {
            id: 5,
            title: "Pin",
            path: "/produits/BOIS-BLANC/1",
            data: {
              id: 4,
              image: "/assets/Pin.jpg",
              images: [
                {
                  img1: "/assets/BbTerrase.jpg",
                  img2: "/assets/BbAbris.jpg",
                  img3: "/assets/BbDecorat.jpg",
                  img4: "/assets/BbDivers.jpg",
                },
              ],
              category: "bois-blanc",
              desc: "Habitat dispose d’un stock important de bois blanc appelé également sapin ou épicéa, importé de Suède et Finlande. C’est une essence légère et résistante, utilisée pour la menuiserie intérieure et extérieure, la fabrication de charpentes, de cadres, de portes et fenêtres ainsi que pour le coffrage.",
              essences: "Épicéa",
              utilisations:
                "Menuiserie intérieure & extérieure, cadres de portes/fenêtres, lamellés-collés, tourets, emballages, palettes, agencement, construction de maison à ossature bois etc.",
              DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
              livraison: "Oui",
              PROVENANCES: "AV-ASIE WOOD-GR-MM-SOCOREG",
              RÉSISTANCE:
                "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
              classes: "I,V,III,Shall,VII",
              long: "3-4",
              epaisseur: "25-->50",
              larg: "75-100-150-200-225",
            },
          },
        ],
      },

      {
        title: "BOIS-DUR",
        icon: "bi-gear-fill",
        childrens: [
          {
            id: 3,
            title: "Chene",
            path: "/produits/BOIS-DUR/1",
            data: {
              id: 4,
              image: "/assets/BdChene.jpg",
              images: [
                {
                  img1: "/assets/BoisDurUse1.jpg",
                  img2: "/assets/BoisDurUse2.jpg",
                  img3: "/assets/BoisDurUse3.jpg",
                  img4: "/assets/BoisDurUse4.jpg",
                },
              ],
              category: "bois-dur",
              desc: "Le plus connu des feuillus durs. Possède un grain fin et une dureté qui varient sensiblement suivant les provenances.En Maroc, utilisé en menuiserie extérieure notamment pour les portes et les fenêtres.Le Chêne est aussi utilisé en décoration, agencement, boiseries avec sculptures, meubles, placages et contreplaqués.Se travaille sans difficulté suivant les différentes duretés.",
              essences: "Chêne",
              utilisations:
                "Menuiserie intérieure & extérieure, cadres de portes/fenêtres, lamellés-collés, tourets, emballages, palettes, agencement, construction de maison à ossature bois etc.",
              DENSITÉ: "740 kg/m3",
              livraison: "Oui",
              PROVENANCES:
                "AP-ARAMA-CEMA-FLORIAN-EXPORTDRVO-MRHL-VASICOS-TROPICA-WLC",
              RÉSISTANCE: "Flexion: 97 Mpa Compression: 58 Mpa",
              classes: "I,V,III,Shall,VII",
              long: "1.2--->4",
              matiere: "Bois",
              epaisseur: "27-40-50-52-80",
              larg: "75-->225",
            },
          },
          {
            id: 4,
            title: "Hetre",
            path: "/produits/BOIS-DUR/1",
            data: {
              id: 4,
              image: "/assets/BdHetre.jpg",
              images: [
                {
                  img1: "/assets/BoisDurUse1.jpg",
                  img2: "/assets/BoisDurUse2.jpg",
                  img3: "/assets/BoisDurUse3.jpg",
                  img4: "/assets/BoisDurUse4.jpg",
                },
              ],
              category: "bois-dur",
              desc: "Utilisation très étendue dans les diverses industries du bois : menuiserie intérieure notamment les portes, ameublement surtout les salons, meubles de cuisine et bibliothèques, articles de ménage, manches d’outils, tournage, charronnage.Se prête facilement au ceintrage. Très robuste est également employé en carcasses de fauteuils et pour la fabrication de sièges, pieds tournés, etc.Prend très facilement les teintes façon acajou, noyer, palissandre. Se décolore même pour imiter le sycomore.Séchage assez délicat à cause d’une forte tendance aux déformations.",
              essences: "Hêtre",
              utilisations:
                "Menuiserie intérieure & extérieure, cadres de portes/fenêtres, lamellés-collés, tourets, emballages, palettes, agencement, construction de maison à ossature bois etc.",
              DENSITÉ: "0,60 à 0,75 – dur",
              livraison: "Oui",
              PROVENANCES:
                "ARAMA-CEMA-FLORIAN-EXPORTDRVO-Ancien-VASICOS-Tropica Bois",
              RÉSISTANCE: "Flexion: 111 Mpa Compression: 57 Mpa",
              classes: "I,V,III,Shall,VII",
              long: "0.3-0.6-0.8-1-2-3-4",
              matiere: "Bois",
              epaisseur: "27-40-50-52-80",
              larg: "75-->225",
            },
          },
          {
            id: 5,
            title: "Iroko",
            path: "/produits/BOIS-DUR/1",
            data: {
              id: 4,
              image: "/assets/BdIroko.jpg",
              images: [
                {
                  img1: "/assets/BoisDurUse1.jpg",
                  img2: "/assets/BoisDurUse2.jpg",
                  img3: "/assets/BoisDurUse3.jpg",
                  img4: "/assets/BoisDurUse4.jpg",
                },
              ],
              category: "bois-dur",
              desc: "Le bois iroko est un bois exotique durable, qui ne nécessite pas de traitement de préservation : il offre donc des avantages économiques et écologiques qui en font un matériau idéal pour l'aménagement extérieur.",
              essences: "padouk-teak-tatajuba",
              utilisations:
                "Menuiseries intérieures. Revêtement de sols. Charpente.",
              DENSITÉ: "0.60 à 0.75 – dur",
              livraison: "Oui",
              PROVENANCES: "Cema(maroc)",
              RÉSISTANCE: "Flexion: 117 Mpa Compression: 64 Mpa",
              classes: "I,V,III,Shall,VII",
              long: "5",
              matiere: "Bois",
              epaisseur: "80",
              larg: "75-->225",
            },
          },
          {
            id: 6,
            title: "Kossipo",
            path: "/produits/BOIS-DUR/1",
            data: {
              id: 4,
              image: "/assets/BdKossipo.jpg",
              images: [
                {
                  img1: "/assets/BoisDurUse1.jpg",
                  img2: "/assets/BoisDurUse2.jpg",
                  img3: "/assets/BoisDurUse3.jpg",
                  img4: "/assets/BoisDurUse4.jpg",
                },
              ],
              category: "bois-dur",
              desc: "L’essence exotique kosipo est un bois de couleur brun rouge à reflets violacés. Il fonce à la lumière. C’est un bois léger à moyennement lourd, tendre à moyennement dur. Il est résistant aux insectes de bois sec, moyennement durable face aux termites. Le bois tropical kosipo risque de pourrir en cas d'humidification même temporaire : il est donc nécessaire de traiter le bois dans les cas d’utilisation avec risque d’humidification temporaire.",
              essences: "Sapelli",
              utilisations:
                "Menuiserie intérieure & extérieure,En ameublement,Pour fabriquer des placages et contreplaqués.",
              DENSITÉ: " 0,75 – dur",
              livraison: "Oui",
              PROVENANCES: "Tropica Bois",
              RÉSISTANCE: "Flexion: 95 Mpa Compression: 50 Mpa",
              classes: "I,V",
              long: "3-->5",
              matiere: "Bois",
              epaisseur: "50",
              larg: "75-->225",
            },
          },
          {
            id: 7,
            title: "Cedre",
            path: "/produits/BOIS-DUR/1",
            data: {
              id: 4,
              image: "/assets/BdCedre.jpg",
              images: [
                {
                  img1: "/assets/BoisDurUse1.jpg",
                  img2: "/assets/BoisDurUse2.jpg",
                  img3: "/assets/BoisDurUse3.jpg",
                  img4: "/assets/BoisDurUse4.jpg",
                },
              ],
              category: "bois-dur",
              desc: "Le cèdre est considéré comme le bois dur domestique le plus résistant aux intempéries. Il est souvent utilisé pour des applications extérieures, mais au fil du temps, il se décompose sous l’effet des éléments, comme tout autre bois sur la planète. À cause de ces facteurs, nous recommandons plutôt le bois pastique recyclé (LPR).",
              essences: "Cedre",
              utilisations:
                "Menuiserie intérieure & extérieure, cadres de portes/fenêtres, lamellés-collés, tourets, emballages, palettes, agencement, construction de maison à ossature bois etc.",
              DENSITÉ: "0,8-dur",
              livraison: "Oui",
              PROVENANCES: "CEMA",
              RÉSISTANCE: "Flexion: 95 Mpa Compression: 50 Mpa",
              classes: "I,V",
              long: "1.2-->4",
              matiere: "Bois",
              epaisseur: "27-40-50-80",
              larg: "75-->225",
            },
          },

          {
            id: 8,
            title: "Frene",
            path: "/produits/BOIS-DUR/1",
            data: {
              id: 4,
              image: "/assets/bdfrene.jpg",
              images: [
                {
                  img1: "/assets/BoisDurUse1.jpg",
                  img2: "/assets/BoisDurUse2.jpg",
                  img3: "/assets/BoisDurUse3.jpg",
                  img4: "/assets/BoisDurUse4.jpg",
                },
              ],
              category: "bois-dur",
              desc: "Le frêne est un bois de couleur blanche, avec des reflets nacrés et parfois un peu rosés. Il est également plus brun au niveau du cœur, mais une fois abattu, il s’assombrit immédiatement. C’est un matériau très élastique, assez dur et résistant qui peut être exploité pour plusieurs usages.",
              essences: "Frene",
              utilisations: "Menuiseries intérieures. Revêtement de sols.",
              DENSITÉ: "0,7-dur",
              livraison: "Oui",
              PROVENANCES: "FLORIAN",
              RÉSISTANCE: "Flexion: 113 Mpa Compression: 51 Mpa",
              classes: "I,V",
              long: "1.2-->4",
              matiere: "Bois",
              epaisseur: "52",
              larg: "75-->225",
            },
          },
          {
            id: 9,
            title: "Dibetou",
            path: "/produits/BOIS-DUR/1",
            data: {
              id: 4,
              image: "/assets/bddibetou.jpg",
              images: [
                {
                  img1: "/assets/BoisDurUse1.jpg",
                  img2: "/assets/BoisDurUse2.jpg",
                  img3: "/assets/BoisDurUse3.jpg",
                  img4: "/assets/BoisDurUse4.jpg",
                },
              ],
              category: "bois-dur",
              desc: "Le dibétou est un arbre connu comme le noyer africain, une espèce qui pousse en Afrique équatoriale, très appréciée par son bois noble: le bois de dibétou.Le bois de dibétou est tendre, au fil droit généralement entrecroisé, et le grain est de fin à moyen. C’est in bois résistant, mi-lourd, moyennement nerveux et à la texture assez fine.",
              essences: "Dibetou",
              utilisations:
                "Contreplaque,Plaquage,AMEUBLEMENT ÉBÉNISTERIE,menuiserie-interieure-amenagement-escalier",
              DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
              livraison: "Oui",
              PROVENANCES: "Tropica Bois",
              RÉSISTANCE: "Flexion: 95 Mpa Compression: 50 Mpa",
              classes:
                "Classe V - à l'intérieur ou sous abri (risque d'humidification)",
              long: "2.1--->5",
              matiere: "Bois",
              epaisseur: "80",
              larg: "75-->225",
            },
          },
          {
            id: 10,
            title: "Acajo",
            path: "/produits/BOIS-DUR/1",
            data: {
              id: 4,
              image: "/assets/bdacajo.jpg",
              images: [
                {
                  img1: "/assets/BoisDurUse1.jpg",
                  img2: "/assets/BoisDurUse2.jpg",
                  img3: "/assets/BoisDurUse3.jpg",
                  img4: "/assets/BoisDurUse4.jpg",
                },
              ],
              category: "bois-dur",
              desc: "Le terme « acajou » fait en réalité référence à un ensemble d’arbres appartenant à la famille des Meliaceae, d’origine tropicale. L’acajou est bien connu pour la couleur particulière de son bois. En effet, il affiche une teinte allant du rose pâle au rouge foncé. En outre, l’acajou est un bois dégageant une odeur puissante. Il s’agit d’une essence très appréciée, notamment par les ébénistes. L’acajou est d’ailleurs considéré comme un bois noble. Poursuivez la lecture de ce guide, pour en savoir un peu plus à son sujet",
              essences: "Acajo",
              utilisations:
                "Ebénisterie. Ameublement, décoration. Placages décoratifs, marqueterie. Lambris et parquets.",
              DENSITÉ: "570 kg/m3",
              livraison: "Oui",
              PROVENANCES: "Ancien-Tropica Bois",
              RÉSISTANCE: "Flexion: 95 Mpa Compression: 50 Mpa",
              classes: "I,V,III,Shall",
              long: "1.5--->4.7",
              matiere: "Bois",
              epaisseur: "50-80",
              larg: "75-->225",
            },
          },
        ],
      },
    ],
  },
  {
    title: "Contre-plaques",
    icon: "bi-gear-fill",

    childrens: [
      {
        id: 11,
        title: "Hetre",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/CpHetre.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "Le contreplaqué Hetre est un panneau multiplis dont la face, l’âme et la contreface sont en okoumé. Léger, résistant et d’une belle couleur rouge claire, il peut être utilisé pour tous types de travaux d’aménagement extérieur ou en milieu humide sous abri tels que les salles de bain, les cuisines, etc… Il est facile à peindre, teinter ou vernir. Disponible en plusieurs formats, épaisseurs et qualités suivant l’usage que vous souhaitez en faire.",
          essences: "Hetre",
          utilisations: "Agencement",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "22-27-36-40-50",
          larg: "700,750,800,850,1220,1530",
        },
      },
      {
        id: 12,
        title: "Chene",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/CpChene.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          classes: "I,V,III,Shall,VII",
          desc: "Le contre-plaqué chêne est un matériau léger contrairement aux panneaux de chêne en bois massif. Ce contre-plaqué est facile à travailler et sera idéal pour la découpe sur-mesure, tout en conservant les traits authentiques du chêne.",
          essences: "Chene",
          utilisations:
            "projets résidentiels, projets hôteliers, bureaux, etc.",
          DENSITÉ: "530 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "22-27-36-40-50",
          larg: "700,750,800,850,1220,1530",
        },
      },
      {
        id: 13,
        title: "Frene",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/CpFrene.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "Panneau d'agencement sur support contreplaqué, replaqué de bois véritable.Noblesse esthétique et décorative du bois « massif »,Placage permettant des finitions vernies ou cirées,Applications Mobilier, agencement intérieur, décoration murale...",
          essences: "Frene",
          utilisations: "Mobilier, agencement intérieur, décoration murale...",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "22-27-36-40-50",
          larg: "700,750,800,850,1220,1530",
        },
      },
      {
        id: 14,
        title: "Eyong",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/eyong.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "Faces extérieures en placage exotique eyong, avec plis intérieurs en placage déroulé peuplier.La surface a une structure marquée et une fibre longitudinale avec ramage régulier.Faces extérieures avec veine du bois longitudinale.Le contreplaqué exotique Panguaneta répond aux programmes du développement durable forestier.",
          essences: "Eyong",
          utilisations: "Emploi intérieur en milieu sec ",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "22-27-36-40-50",
          larg: "700,750,800,850,1220,1530",
        },
      },

      {
        id: 16,
        title: "Acajo",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/CpAcajo.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "Contreplaqué en Acajou certifié Rina est est un panneau de pointe de notre production de panneaux multi-plis. Forte d'une tradition et d'un patrimoine nautique qui ne nécessitent pas d'introductions, c'est le produit le plus approprié pour la construction, le refit et la finition des bateaux les plus prestigieux, en particulier des bateaux d'époque et classiques.",
          essences: "Sapelli déroulé",
          utilisations: "Industrie nautique,",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "22-27-36-40-50",
          larg: "700,750,800,850,1220,1530",
        },
      },
      {
        id: 17,
        title: "Fromager",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/Fromager.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "Panneau de contreplaqué en fromager pour travaux de menuiserie ou d’agencement. Permet la réalisation de formes galbées, circulaires ou semi-circulaires. Composé de trois plis croisés de fromager à deux faces poncées, sans traitement chimique. Collage classe 1. Proposé en 7 ou 9 mm d'épaisseur pour 2,5 mètres de longueur.",
          essences: "Fromajer",
          utilisations:
            "Menuiserie, Ameublement, Agencement, Ebénisterie, Transport, Construction, Plancher, Rayonnage,Emballage.",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Spain",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "22-27-36-40-50",
          larg: "700,750,800,850,1220,1530",
        },
      },
      {
        id: 18,
        title: "Ilomba",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/CpIlomba.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "Panneau généraliste, il est utilisé dans de multiples applications industrielles comme l'aménagement intérieur de caravane ou de véhicules utilitaires où il est apprécié pour son excellent rapport qualité/prix/usage.",
          essences: "ilomba",
          utilisations:
            "Mobilier,MEUBLES,AMEUBLEMENT,PORTES Et Jambages,CARAVANE",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Spain",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "22-27-36-40-50",
          larg: "700,750,800,850,1220,1530",
        },
      },
      {
        id: 19,
        title: "Dibetou",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/CpDibotou.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "Le dibétou est une essence de bois exotique originaire d'Afrique. Bois brun jaune ou brun gris, strié ou veiné de noir, c'est un matériau moyennement ou faiblement durable, principalement utilisé en menuiserie intérieure et en ébénisterie",
          essences: "dibetou",
          utilisations:
            "Structure et habillage,Menuiserie et aménagement,Utilisations diverses ",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "22-27-36-40-50",
          larg: "700,750,800,850,1220,1530",
        },
      },
      {
        id: 20,
        title: "Okoumé",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/CpOkoume.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "Stable, performant et résistant, le contre-plaqué Okoumé CTB-X sur-mesure est particulièrement apprécié pour sa densité et sa double utilisation intérieure/extérieure.Idéal pour la découpe sur-mesure, ce contre-plaqué est recommandé pour les ouvrages extérieurs, soumis à une exposition prolongée aux intempéries ou à l’eau.",
          essences: "Okoume",
          utilisations: "Mobilier, agencement intérieur, décoration murale...",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "80-120-150",
          larg: "700,750,800,850,1220,1530",
        },
      },
      {
        id: 21,
        title: "Zebrano",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/CPZebrano.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "contre-plaqué de fantaisie de haute qualité avec des couleurs très gentilles de placage en bois normal par des techniques exquises. Emballage standard d'exportation en liant avec le contre-plaqué et intérieur enveloppé par la feuille de plastique",
          essences: "zebrano",
          utilisations: "Mobilier, agencement intérieur, décoration murale...",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "40",
          larg: "700,750,800,850,1220,1530",
        },
      },
      {
        id: 22,
        title: "Noyer",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/CPNoyer.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "Panneau contreplaqué plaqué Noyer Panneau d'agencement sur support contreplaqué, replaqué de bois véritable. Noblesse esthétique et décorative du bois « massif » Placage permettant des finitions vernies ou cirées Applications Mobilier, agencement intérieur, décoration murale... ",
          essences: "noyer",
          utilisations: "Mobilier, agencement intérieur, décoration murale...",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "40",
          larg: "1220",
        },
      },

      {
        id: 23,
        title: "Latté",
        path: "/produits/Contre-Plaques/4",
        data: {
          id: 4,
          image: "/assets/CpLatte.jpg",
          images: [
            {
              img1: "/assets/CpUse1.jpg",
              img2: "/assets/CpUse2.jpg",
              img3: "/assets/CpUse3.jpg",
              img4: "/assets/CpUse4.jpg",
            },
          ],
          category: "contre-plaques",
          desc: "Le contreplaqué latté est complètement différent des autres types de contreplaqués en raison de sa structure. Il est constitué d’une ou plusieurs couches de lattes de bois collées les unes aux autres et recouvertes sur chaque face, d’une feuille de placage. Idéal pour les travaux de menuiserie, d’agencement et la fabrication de meubles. Disponible en plusieurs essences et épaisseurs.",
          essences:
            "Fromager, Chêne, Hêtre, Acajou, Frêne, Merisier, Zebrano, Padouk, Noyer, Iroko, Dibetou",
          utilisations: "Menuiserie, Agencement, Mobilier",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "20",
          larg: "700,750,800,850,1220,1530",
        },
      },
    ],
  },
  {
    title: "PANNEAU",
    icon: "bi-gear-fill",
    childrens: [
      {
        title: "Stratidécor",
        path: "/produits/Panneaux/4",
        data: {
          id: 4,
          image: "/assets/PanStratidécor.jpg",
          images: [
            {
              img1: "/assets/StratidecorUse1.jpg",
              img2: "/assets/StratidecorUse2.jpg",
              img3: "/assets/StratidecorUse3.jpg",
              img4: "/assets/StratidecorUse4.png",
            },
          ],
          category: "panneaux",
          desc: "Le panneau particule ou aggloméré est constitué de particules de bois collées entre elles: les fragments de bois sont mélangés à une résine et pressés à chaud. Les faces peuvent être recouvertes d’un parement décoratif en placage bois ou en résine de mélamine ou synthétique avec de nombreuses finitions. La composition de la colle est modifiée pour pouvoir rendre le panneau résistant à l’eau ou au feu.",
          essences: "Pin, Eucalyptus, Sapin, Peuplier",
          utilisations:
            " Cuisines, Meubles, Mobilier, muraux, Portes, Revêtements",
          DENSITÉ: "600 et 800 kg/m3",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Turquie",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.5",
          matiere: "bois",
          epaisseur: "8-16-19",
          larg: "1800",
        },
      },
      {
        title: "Stratibois",
        path: "/produits/Panneaux/4",
        data: {
          id: 4,
          image: "/assets/PanStratibois.jpg",
          images: [
            {
              img1: "/assets/StratiboisUse1.jpg",
              img2: "/assets/StratiboisUse3.jpg",
              img3: "/assets/StratiboisUse4.jpg",
              img4: "/assets/StratiboisUse5.jpg",
            },
          ],
          category: "panneaux",
          desc: "Le panneau particule ou aggloméré est constitué de particules de bois collées entre elles: les fragments de bois sont mélangés à une résine et pressés à chaud. Les faces peuvent être recouvertes d’un parement décoratif en placage bois ou en résine de mélamine ou synthétique avec de nombreuses finitions. La composition de la colle est modifiée pour pouvoir rendre le panneau résistant à l’eau ou au feu.",
          essences: "Pin, Eucalyptus, Sapin, Peuplier",
          utilisations:
            "Cloisons intérieures, Menuiserie, Meubles, Placards, Portes ",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Turquie",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.44",
          matiere: "bois",
          epaisseur: "8-16-19",
          larg: "1220-->1700",
        },
      },
      {
        title: "Stratifié",
        path: "/produits/Panneaux/4",
        data: {
          id: 4,
          image: "/assets/PanStratifie.jpg",
          images: [
            {
              img1: "/assets/StratiboisUse1.jpg",
              img2: "/assets/StratiboisUse3.jpg",
              img3: "/assets/StratiboisUse4.jpg",
              img4: "/assets/StratiboisUse5.jpg",
            },
          ],
          category: "panneaux",
          desc: "Terrasses et jardins s’offrent une esthétique naturelle avec cette dalle béton aspect bois, qui résiste aux intempéries et offre un réel confort de pose et d’entretien.Posée sur sable, la dalle Novabois T7 / T11 est carrossable.",
          essences: "Pin, Eucalyptus, Sapin, Peuplier",
          utilisations:
            " Cuisines, Meubles, Mobilier, muraux, Portes, Revêtements",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Turquie",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.5",
          matiere: "bois",
          epaisseur: "8-16-19",
          larg: "1800",
        },
      },
      {
        title: "MDF Mélaminé",
        path: "/produits/Panneaux/4",
        data: {
          id: 4,
          image: "/assets/PanMdfMelamini.jpg",
          images: [
            {
              img1: "/assets/StratiboisUse1.jpg",
              img2: "/assets/StratiboisUse3.jpg",
              img3: "/assets/StratiboisUse4.jpg",
              img4: "/assets/StratiboisUse5.jpg",
            },
          ],
          category: "panneaux",
          desc: "Terrasses et jardins s’offrent une esthétique naturelle avec cette dalle béton aspect bois, qui résiste aux intempéries et offre un réel confort de pose et d’entretien.Posée sur sable, la dalle Novabois T7 / T11 est carrossable.",
          essences: "Pin, Eucalyptus, Sapin, Peuplier",
          utilisations:
            "Agencement, cuisine, menuiserie, décoration intérieure",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Turquie",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.8",
          matiere: "bois",
          epaisseur: "8-18",
          larg: "2100",
        },
      },
      {
        title: "Mdf Brut",
        path: "/produits/Panneaux/4",
        data: {
          id: 4,
          image: "/assets/PanMdfBrut.png",
          images: [
            {
              img1: "/assets/StratiboisUse1.jpg",
              img2: "/assets/StratiboisUse3.jpg",
              img3: "/assets/StratiboisUse4.jpg",
              img4: "/assets/StratiboisUse5.jpg",
            },
          ],
          category: "panneaux",
          desc: "Terrasses et jardins s’offrent une esthétique naturelle avec cette dalle béton aspect bois, qui résiste aux intempéries et offre un réel confort de pose et d’entretien.Posée sur sable, la dalle Novabois T7 / T11 est carrossable.",
          essences: "Pin, Eucalyptus",
          utilisations:
            "Menuiserie, agencement, décoration intérieure, cuisine",
          DENSITÉ: "600 et 800 kg/m3",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Turquie",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "3.66",
          matiere: "bois",
          epaisseur: "5-6-7-8-10-12-15-18",
          larg: "2700",
        },
      },
      {
        title: "High Gloss",
        path: "/produits/Panneaux/4",
        data: {
          id: 4,
          image: "/assets/PanHighGloss.jpg",
          images: [
            {
              img1: "/assets/StratiboisUse1.jpg",
              img2: "/assets/StratiboisUse3.jpg",
              img3: "/assets/StratiboisUse4.jpg",
              img4: "/assets/StratiboisUse5.jpg",
            },
          ],
          category: "panneaux",
          desc: "Terrasses et jardins s’offrent une esthétique naturelle avec cette dalle béton aspect bois, qui résiste aux intempéries et offre un réel confort de pose et d’entretien.Posée sur sable, la dalle Novabois T7 / T11 est carrossable.",
          essences: "Pin, Eucalyptus, Sapin, Peuplier",
          utilisations:
            " Cuisines, Meubles, Mobilier, muraux, Portes, Revêtements",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Turquie",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall,VII",
          long: "2.8",
          matiere: "bois",
          epaisseur: "18",
          larg: "1220",
        },
      },
      {
        title: "Latté",
        path: "/produits/Panneaux/4",
        data: {
          id: 4,
          image: "/assets/CpLatte.jpg",
          images: [
            {
              img1: "/assets/StratiboisUse1.jpg",
              img2: "/assets/StratiboisUse3.jpg",
              img3: "/assets/StratiboisUse4.jpg",
              img4: "/assets/StratiboisUse5.jpg",
            },
          ],
          category: "panneaux",
          desc: "Latté est complètement différent des autres types de contreplaqués en raison de sa structure. Il est constitué d’une ou plusieurs couches de lattes de bois collées les unes aux autres et recouvertes sur chaque face, d’une feuille de placage. Idéal pour les travaux de menuiserie, d’agencement et la fabrication de meubles. Disponible en plusieurs essences et épaisseurs.",
          essences:
            "Âme:Fromager ou Okoumé Face/Contre-face:Fromager, Chêne, Hêtre, Acajou, Frêne, Merisier, Zebrano, Padouk, Noyer, Iroko, Dibetou",
          utilisations: "Menuiserie, Agencement, Mobilier",
          DENSITÉ: "440 kg/m3 (lorsque sec à 12%)",
          livraison: "Oui",
          PROVENANCES: "Maroc,Spain,Chine",
          RÉSISTANCE: "Flexion : 75 Mpa Traction : 90 Mpa Compression : 40 Mpa",
          classes: "I,V,III,Shall",
          long: "2.2-2.5",
          matiere: "bois",
          epaisseur: "2",
          larg: "700,750,800,850,1220,1530",
        },
      },
    ],
  },
];
export default data;
