export const BOIS_DETAILS_REQUEST = "BOIS_DETAILS_REQUEST";
export const BOIS_DETAILS_SUCCESS = "BOIS_DETAILS_SUCCESS";
export const BOIS_DETAILS_FAIL = "BOIS_DETAILS_FAIL";

export const CHAND_DETAILS_REQUEST = "CHAND_DETAILS_REQUEST";
export const CHAND_DETAILS_SUCCESS = "CHAND_DETAILS_SUCCESS";
export const CHAND_DETAILS_FAIL = "CHAND_DETAILS_FAIL";
